name: e2e pipeline

on:
  workflow_dispatch:
    
jobs:
  Google_Execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Runs Google Page Test Cases
        run: mvn test -Dgroups=google

  Apex_Execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Runs Google Page Test Cases
        run: mvn test -Dgroups=apex
