name: Scheduled pipeline

on:
  schedule:
    - cron: "0 5,17 * * 1-5"

jobs:
  Google_Execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Runs Google Page Test Cases
        run: mvn test -Dgroups=google
      - name: Upload Report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: googleReport
          path: test-output/**
          if-no-files-found: error
          retention-days: 90

  Apex_Execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Runs Apex Page Test Cases
        run: mvn test -Dgroups=apex
      - name: Upload Report
        uses:  actions/upload-artifact@v4.3.1
        with:
          name: apexReport
          path: test-output/**
          if-no-files-found: error
          retention-days: 90
